version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20 # Ensure Docker is available in the environment
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Log in to the Amazon ECR registry
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 806263047535.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=806263047535.dkr.ecr.ap-southeast-1.amazonaws.com/kia-image
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo Repository URI: $REPOSITORY_URI
      - echo Image Tag: $IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      # Build the Docker image using the Dockerfile
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      # Tag the Docker image with the 'latest' tag
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      # Push the tagged image to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - '**/*'
