apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afsb-dtp-staging-eks-ingress
annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - hosts: "foo.bar.com"
    http:
      paths:
      - path: /test-path
        pathType: Prefix   # Required field in networking.k8s.io/v1
        backend:
          service:
            name: afsb-dtp-staging-eks-service
            port:
              number: 80
