apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: afsb-dtp-staging-eks-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /test-path
        backend:
          serviceName: afsb-dtp-staging-eks-service
          servicePort: 80
