apiVersion: v1
kind: Service
metadata:
  name: afsb-dtp-staging-eks-service
spec:
  selector:
    app: afsb-dtp-staging-eks-service
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port your container is listening on
  type: LoadBalancer
